services:
  hotels.apigateway:
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}hotelsapigateway
    depends_on:
      - hotels.database
    build:
      context: .
      dockerfile: Hotels.ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    ports:
      - "5001:8080"
      - "5002:8081"


  hotels.bookingsservice:
    container_name: bookingsservice
    image: ${DOCKER_REGISTRY-}hotelsbookingsservice
    depends_on:
      - hotels.database
    build:
      context: .
      dockerfile: BookingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    ports:
      - "5005:8080"
      - "5006:8081"


  hotels:
    container_name: monolith
    image: ${DOCKER_REGISTRY-}hotels
    depends_on:
      - hotels.database
    build:
      context: .
      dockerfile: Hotels/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    ports:
      - "5003:8080"
      - "5004:8081"


  hotels.partnerreviews:
    container_name: partner_reviews_service
    image: ${DOCKER_REGISTRY-}hotelspartnerreviews
    depends_on:
      - hotels.database
    build:
      context: .
      dockerfile: Hotels.PartnerReviews/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    ports:
      - "5007:8080"
      - "5008:8081"


  hotels.database:
    container_name: hotels.database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Keras2310!
    ports:
      - "5432:5432"


  hotels.partnerreviews.db:
    container_name: partner_reviews_database
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: mongo
        MONGO_INITDB_ROOT_PASSWORD: Keras2310!
    ports:
      - "8081:8081"
